import { registerAbility } from '../abilityRegistry';
import { createNoopAbility } from './abilityFactories';

registerAbility(createNoopAbility({ name: "(+2 health) Fire aura", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+2 health) Haste", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+2 health) Windblast", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+3 health) Gr. heal", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+4 health) Charm", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+4 health) Refresh", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+5 health) Courage", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "(+5 health) Curse", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Acolyte", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Atonement", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Backdraft", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Berserker", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Blind", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Blindstrike", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Blink", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Blood archer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Call of nature", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Channel", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Cistene's chattels", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Cly's adornments", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Compulsion", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Confound", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Constrictor", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Convulsions", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Corrode", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Counter", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Coup de grace", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Crawlers", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Cruel twist", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Cunning", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Deceieve", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Defender", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Dirge", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Doom", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Drake", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Druid", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Eureka!", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Faith", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Faith & duty", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Faithful friend", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Fear", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Fiend's finest", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Finery of the fallen", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Fire shield", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Flurry", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Fortitide", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Frost bite", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Frostbite", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Geomancer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Gorilla rage", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Gouge", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Greater heal", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Head shot", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Heartless", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Heavy blow", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "High five!", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Hooked", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Hypnotise", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Icelock", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Insight", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Insulated", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Last defence", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Lifespark", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Mangle", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Medic", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Melt", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Missionary's calling", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Monkey mob", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Near death", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Necromancer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Nightwalker set", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Packmaster", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Pagan's spirit", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Parasite", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Penance", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Primal", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Purge", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Pyromancer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Reaper", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Reckless", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Resolve", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Roll with it", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Royal regalia set", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Runecaster", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Safe path", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Savage arms", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Savage call", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Scholar", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Seraphim's symbols", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Shatter", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Shunt", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Silverfrost", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Siphon", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Skewer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Slick", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Sneak", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Spindlesilk set", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Spirt hunter", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Stagger", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Suppress", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Sure edge", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Sure grip", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Swarm", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Sweet spot", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Timeshift", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Titan", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Turn up the heat", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Underhand", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Unstoppable", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Veil", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Venommancer", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Volley", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Vortex", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Wave", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Weaver", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Wisdom", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Wish master", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "Wither", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "finery of the fallen", description: "Not implemented yet." }));
registerAbility(createNoopAbility({ name: "frostbite", description: "Not implemented yet." }));

